[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
# Environment variables to set in Railway dashboard
# API_ID = "your_api_id"
# API_HASH = "your_api_hash"
# BOT_TOKEN = "your_bot_token"
# ADMIN_ID = "your_admin_id"
# DATABASE_URL = "postgresql://user:password@host:port/database"
# REPLIT_URL = "https://your-repl.username.repl.co"
# PORT = "8080"
# RAILWAY_DEPLOYMENT = "true"